# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow', '0003_auto_20171204_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='initial_prefetch',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Object_Type'),
        ),
    ]
