# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow', '0004_workflow_initial_prefetch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transition',
            unique_together=set([('name', 'final_state')]),
        ),
    ]
