# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow', '0005_auto_20180104_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Description'),
        ),
    ]
