# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow', '0006_transition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
