# Generated by Django 2.0 on 2018-01-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow', '0008_auto_20180117_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackparameter',
            name='callback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='django_workflow.Callback', verbose_name='Callback'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='initial_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transitions', to='django_workflow.State', verbose_name='Initial State'),
        ),
    ]
