# Generated by Django 2.0 on 2018-02-26 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow', '0008_auto_20180117_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitionlog',
            name='object_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_workflow.CurrentObjectState', verbose_name='Object State'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='initial_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transitions', to='django_workflow.State', verbose_name='Initial State'),
        ),
    ]
