# Generated by Django 2.0.1 on 2018-03-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow', '0009_auto_20180226_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitionlog',
            name='object_state',
        ),
    ]
