# Generated by Django 2.1.1 on 2018-09-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow', '0012_auto_20180919_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statevariabledef',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variable_definitions', to='django_workflow.State', verbose_name='State'),
        ),
    ]
