# Generated by Django 2.0.1 on 2018-10-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow', '0013_auto_20180925_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Label'),
        ),
    ]
