# Generated by Django 2.1 on 2019-10-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow', '0014_transition_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='condition_type',
            new_name='condition_typ',
        ),
    ]
