# Generated by Django 2.1 on 2019-10-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow', '0015_auto_20191015_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='condition_typ',
            new_name='condition_opt',
        ),
    ]
